name: Build and test nari

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Use Node.js 18.x"
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: "Install nari"
        run: |
          npm i -g nari

      - name: Install, build, lint and test
        run: |
          nari
          nari prepack
